use_gpu = false
device_id = 1
funcaptcha_server = "http://localhost:8081"
client_key = "your_api_key"
headless = true
proxy_bridge_url = "http://localhost:8080"
proxy_bridge_host = "localhost"
proxy_bridge_api_key = "your_api_key"
drission_page_headless = false
debug_screen = false
virtual_browser_worker_start = 1
virtual_browser_worker_end = 100